# Site settings
title: HUANJU LU
email: huanjulu@outlook.com
description: "My name is Huanju. I'm a software developer specializing in Java, Python and AWS. I have a website that I developed independently using React and JavaScript. I like new technologies and have experience in solving problems in real-world scenarios."
baseurl: ""
url: ""
username: Huanju
timezone: America/Seattle
twitter_username: 

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  tags:
    output: true
