# Site settings
title: HUANJU LU
email: huanjulu@outlook.com
description: "I am comfortable specializing in full-stack, backend and SRE field with Java, Python, Go, JavaScript, AWS Cloud. I am always eager to learn new technologies and tools, and I am committed to staying up-to-date with the latest trends and best practices in the field."
baseurl: ""
url: ""
username: Huanju
timezone: America/Seattle
twitter_username: 

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  tags:
    output: true
