# Site settings
title: HUANJU LU
email: huanjulu@outlook.com
description: "My name is Huanju. I'm a software developer specializing in Python, Django, Vue.js, and AWS. I lead software teams and mentor others to become leaders themselves."
baseurl: ""
url: "http://www.grantmcconnaughey.com"
username: grantmcconnaughey
timezone: America/Chicago
twitter_username: gmcconnaughey

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# https://kylewbanks.com/blog/creating-category-pages-in-jekyll-without-plugins
collections:
  tags:
    output: true
